name: "Bug Report"
description: "Create a report to help us improve"
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Description

        A clear and concise description of what the bug is.
  
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happens.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide the following information:
        - Firmware version:
        - Hardware:
        - Toolchain:
        - Additional software:

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
