name: "Feature Request"
description: "Suggest an idea for this project"
title: "[Feature Request] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Description

        Please provide a clear and concise description of the feature you are requesting.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed and what problem it solves. If applicable, describe the current behavior and the expected behavior.

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe how you think this feature should be implemented. Include any relevant details, examples, or diagrams.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List and describe any alternative solutions or features you've considered.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
