name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v23

      - name: Run Super-Linter
        uses: actions/checkout@v23

        env:
            DEFAULT_BRANCH: main
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
