################################
# @author: Mohamed Wx
# @brief: Testing github actions
#
################################
name: Testing

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        c_std: [c99]

    env:
      MODE: "dev"

    steps:
      - uses: actions/checkout@v3

      # Setup the compiler
      - name: Set up GCC Compiler & Makefile Utility
        run: |
          echo "Installing gcc..."
          sudo apt-get update
          sudo apt-get install -y gcc
          sudo apt-get install -y make

      # Build
      - name: Build & Run the library
        run: |
          echo "Starting build process..."
          echo "Current working directory: $(pwd)"
          echo "List files in the directory:"
          ls -al
          bash ./build.sh
